### ISSUE TITLE
Race condition on start right now

### ISSUE THREAD

**Issue by jwu910** [the-after-hours/contri-credit#1]
`node index.js` will sometimes throw

```
  userList.map(user => {
           ^

TypeError: userList.map is not a function
    at Request._callback (/home/joshua/programming/contri-credit/index.js:30:12)
    at Request.self.callback (/home/joshua/programming/contri-credit/node_modules/request/request.js:185:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/joshua/programming/contri-credit/node_modules/request/request.js:1161:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/joshua/programming/contri-credit/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)

```

**Comment by rainrivas** [comment]
This probably because we called `JSON.parse` any reason why we parse the data and don't interface with it raw?

**Comment by jwu910** [comment]
Haven't been able to reproduce with current development https://github.com/the-after-hours/contri-credit/pull/2

**Comment by rainrivas** [comment]
@jwu910 might've just been an issue with callback nature of `request` vs promise nature of `axios`
lets close this out after we merge?
